server:
  port: 8080

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.messaging: DEBUG

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/iot"
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: validate
    show_sql: true